# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Invenio Services is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  redis:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD=invenio"
      - "MYSQL_DATABASE=invenio"
      - "MYSQL_USER=invenio"
      - "MYSQL_PASSWORD=invenio"
    ports:
      - "3306:3306"
  psql:
    image: postgres:9.6
    restart: "always"
    environment:
      - "POSTGRES_USER=invenio"
      - "POSTGRES_PASSWORD=invenio"
      - "POSTGRES_DB=invenio"
    ports:
      - "5432:5432"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ESV}
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.data=true
      - network.host=0.0.0.0
      - discovery.seed_hosts=[]
      - cluster.initial_master_nodes=[]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9300:9300"
